#include "hades/crud.hpp"
#include "hades/crud/destroy.ipp"
#include "hades/crud/destroy_collection.ipp"
#include "hades/crud/exists.ipp"
#include "hades/crud/from_id.ipp"
#include "hades/crud/get_collection.ipp"
#include "hades/crud/insert.ipp"
#include "hades/crud/overwrite_collection.ipp"
#include "hades/crud/save.ipp"
#include "hades/crud/save_collection.ipp"
#include "hades/crud/update.ipp"

